hamlet/citations/urls.py
from django.urls import path

from . import views

app_name = 'citations'

urlpatterns = [
    path('lit_review_buddy/',
        views.LitReviewBuddyView.as_view(), name='lit_review_buddy'),
]

hamlet/theses/urls.py
from django.urls import path

from . import views

app_name = 'theses'

urlpatterns = [
    path('similar_to/',
        views.SimilarToSearchView.as_view(), name='similar_to'),
    path('similar_to/<int:identifier>/',
        views.SimilarToView.as_view(), name='similar_to'),
    path('similar_to/author/<int:pk>/',
        views.SimilarToByAuthorView.as_view(), name='similar_to_by_author'),
    path('autocomplete/author/',
        views.AutocompleteAuthorView.as_view(), name='autocomplete_author'),
    path('autocomplete/thesis/',
        views.AutocompleteThesisView.as_view(), name='autocomplete_thesis'),
    path('upload/recommend/',
        views.UploadRecommendationView.as_view(), name='upload_recommend'),
]

hamlet/urls.py
from django.urls import include, path
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('about/',
        TemplateView.as_view(template_name='about.html'), name='about'),
    # Note that URLs imported from theses all have top-level URL paths!
    # Because they're the meat of the application there's no reason to add
    # cruft to the URL.
    path(r'', include('hamlet.theses.urls')),
    path(r'citations/', include('hamlet.citations.urls')),
    path('captcha/', include('captcha.urls')),
    path('health/', include('health_check.urls')),
    path(
        'robots.txt',
        TemplateView.as_view(template_name='robots.txt', content_type='text/plain'),
    ),
]

hamlet/citations/models.py
from django.db import models

from hamlet.theses.models import Thesis


class Citation(models.Model):
    doi = models.CharField(max_length=66, blank=True)
    journal = models.TextField(blank=True)
    url = models.URLField(blank=True)
    author = models.TextField(blank=True)
    title = models.TextField(blank=True)
    isbn = models.CharField(max_length=20, blank=True)
    publisher = models.CharField(max_length=32, blank=True)
    year = models.CharField(max_length=4, blank=True)
    raw_ref = models.TextField()

    # Ultimately this will want to be a many-to-many relationship with
    # Thesis. However, right now Thesis metadata is in a somewhat broken
    # state, and it will be easier to fix if we maintain the option of dumping
    # the production Thesis table into the test one and going from there.
    # Citations can't be ManyToMany with Theses before metadata cleanup
    # happens on the citation side anyway, so putting the relationship here
    # doesn't block anything.
    thesis = models.ForeignKey(Thesis, on_delete=models.CASCADE)

    def __str__(self):
        return self.raw_ref

    class Meta:
        ordering = ['raw_ref']

hamlet/common/forms.py
from captcha.fields import CaptchaField

from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
from django.utils.deconstruct import deconstructible


# By analogy with django.core.validators.FileExtensionValidator source.
@deconstructible
class MimetypeValidator:
    message = "The MIME type is not valid (it appears to be '%(mimetype)s'). Allowed MIME types are: '%(allowed_mimetypes)s'."  # noqa

    def __init__(self, allowed_mimetypes=None):
        if allowed_mimetypes is not None:
            allowed_mimetypes = [allowed_mimetype.lower() for allowed_mimetype in allowed_mimetypes]  # noqa
        self.allowed_mimetypes = allowed_mimetypes

    def __call__(self, value):
        if value.content_type not in self.allowed_mimetypes:
            raise ValidationError(self.message %
                {'mimetype': value.content_type,
                 'allowed_mimetypes': ', '.join(self.allowed_mimetypes)})


@deconstructible
class FileSizeValidator:
    message = 'The file is too large (%(size)s KB). The maximum file size is %(allowed_size)s KB.'  # noqa

    def __init__(self, max_size=2 * 1024 * 1024):
        self.max_size = max_size

    def __call__(self, value):
        if len(value) >= self.max_size:
            raise ValidationError(self.message %
                {'size': round(len(value) / 1024),
                 'allowed_size': round(self.max_size / 1024)})


class UploadFileForm(forms.Form):
    allowed_extensions = ['txt', 'docx']
    allowed_mimetypes = ['text/plain',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document']  # noqa
    max_size = 4 * 1024 * 1024

    file = forms.FileField(
        validators=[FileSizeValidator(max_size),
                    FileExtensionValidator(allowed_extensions),
                    MimetypeValidator(allowed_mimetypes)],
        widget=forms.ClearableFileInput(attrs={'class': 'field field-upload'}),
        help_text='.txt or .docx only.')
    captcha = CaptchaField(help_text='Sorry, no spammers.')

hamlet/theses/forms.py
from dal import autocomplete

from django import forms

from .models import Thesis, Person


class AuthorAutocompleteForm(forms.ModelForm):
    author = forms.ModelChoiceField(
        queryset=Person.objects.all(),
        widget=autocomplete.ModelSelect2(
            url='theses:autocomplete_author',
            attrs={'class': 'field field-text form-input'}),
        label='By author'
    )

    class Meta:
        model = Person
        fields = ()


class TitleAutocompleteForm(forms.ModelForm):
    title = forms.ModelChoiceField(
        queryset=Thesis.objects.filter(unextractable=False),
        widget=autocomplete.ModelSelect2(url='theses:autocomplete_thesis'),
        label='By title'
    )

    class Meta:
        model = Thesis
        fields = ('title',)

hamlet/citations/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView

from hamlet.common.document import factory
from hamlet.common.forms import UploadFileForm
from hamlet.common.inferred_vectors import get_similar_documents


class LitReviewBuddyView(FormView):
    template_name = 'citations/lit_review_buddy.html'
    form_class = UploadFileForm

    def form_valid(self, form):
        context = {}
        doc = factory(self.request.FILES['file'])
        simdocs = get_similar_documents(doc)
        context['suggestions'] = simdocs
        context['total_suggestions'] = sum([
            doc.citation_set.count() for doc in simdocs
        ])
        return render(self.request, 'citations/lit_review_outcomes.html',
            context)

hamlet/theses/views.py
from dal import autocomplete

from django.contrib import messages
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView

from hamlet.common.document import factory
from hamlet.common.forms import UploadFileForm
from hamlet.common.inferred_vectors import get_similar_documents

from .forms import TitleAutocompleteForm, AuthorAutocompleteForm
from .models import Thesis, Person, Contribution


class SimilarToView(DetailView):
    """Given a Thesis, shows the most similar Theses."""
    template_name = 'theses/similar_to.html'

    def get_context_data(self, **kwargs):
        context = super(SimilarToView, self).get_context_data(**kwargs)

        thesis = self.get_object()
        if thesis.unextractable:
            context['unextractable'] = True
        else:
            context['suggestions'] = thesis.get_most_similar(topn=10)

        return context

    def get_object(self, queryset=None):
        identifier = self.kwargs.get('identifier', None)

        try:
            return Thesis.objects.get(identifier=identifier)
        except Thesis.DoesNotExist:
            raise Http404('No matching thesis was found')


class SimilarToByAuthorView(DetailView):
    """Given an author, shows the most similar theses to all of their works."""
    template_name = 'theses/similar_to_by_authors.html'
    model = Person

    def get_context_data(self, **kwargs):
        context = super(SimilarToByAuthorView, self).get_context_data(**kwargs)
        context['theses'] = []

        theses = self.get_theses()
        for thesis in theses:
            if thesis.unextractable:
                context['theses'].append({
                    'object': thesis,
                    'unextractable': True
                })
            else:
                context['theses'].append({
                    'object': thesis,
                    'suggestions': thesis.get_most_similar(topn=10)
                })

        return context

    def get_theses(self):
        contribs = Contribution.objects.filter(
            person=self.get_object(), role=Contribution.AUTHOR)

        return Thesis.objects.filter(contribution__in=contribs)


class SimilarToSearchView(TemplateView):
    """Enter a thesis or author so that the SimilarToViews can find it."""
    template_name = 'theses/search.html'

    def _handle_author(self, pk):
        try:
            author = Person.objects.get(pk=pk)
            url = reverse('theses:similar_to_by_author',
                          kwargs={'pk': author.pk})
            return HttpResponseRedirect(url)
        except Person.DoesNotExist:
            messages.error('No such author.')
            return HttpResponseRedirect('')

    def _handle_thesis(self, pk):
        thesis = Thesis.objects.get(pk=pk)
        url = thesis.get_absolute_url()
        return HttpResponseRedirect(url)

    def get_context_data(self, **kwargs):
        context = super(SimilarToSearchView, self).get_context_data(**kwargs)
        context['title_form'] = TitleAutocompleteForm
        context['author_form'] = AuthorAutocompleteForm
        return context

    def post(self, request, *args, **kwargs):
        if 'author' in request.POST:
            return self._handle_author(request.POST['author'])
        elif 'title' in request.POST:
            return self._handle_thesis(request.POST['title'])
        else:
            messages.warning('Please submit an author or title.')
            return HttpResponseRedirect('')


class AutocompleteAuthorView(autocomplete.Select2QuerySetView):
    """enter a thesis so that the SimilarToView can find it"""
    def get_queryset(self):
        qs = Person.objects.filter(
            contribution__role=Contribution.AUTHOR).distinct()

        if self.q:
            qs = qs.filter(name__icontains=self.q)

        return qs


class AutocompleteThesisView(autocomplete.Select2QuerySetView):
    """enter a thesis so that the SimilarToView can find it"""
    def get_queryset(self):
        qs = Thesis.objects.filter(unextractable=False).distinct()

        if self.q:
            qs = qs.filter(title__icontains=self.q)

        return qs


class UploadRecommendationView(FormView):
    template_name = 'theses/upload_recommend.html'
    form_class = UploadFileForm

    def form_valid(self, form):
        context = {}
        doc = factory(self.request.FILES['file'])
        context['suggestions'] = get_similar_documents(doc)
        return render(self.request, 'theses/similar_to.html', context)

hamlet/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h2>About hamlet</h2>

<p>
  Hamlet uses machine learning to power experimental, exploratory interfaces to the MIT thesis collection.
</p>

<p>
  It is <i>extremely</i> in alpha right now. Some of the interfaces are not yet written; there has been no UX consideration; the server may break at any time without warning. Check back to see how hamlet grows! You can <a href="mailto:andromeda.yelton@gmail.com?subject=hamlet feedback">send feedback to Andromeda Yelton</a>.
</p>

<ul class="list-inline-pipe">
  <li><a href="#how-it-works">How it works</a></li>
  <li><a href="#team">Who made this</a></li>
  <li><a href="#tech">The tech stack</a></li>
</ul>

<hr />

<h3><a id="how-it-works"></a>How it works</h3>
<p>
  Hamlet is based on paragraph vectors (<a href="https://arxiv.org/pdf/1405.4053v2.pdf">Le and Mikolov (2014)</a>), which extend the word2vec algorithm (<a href="https://en.wikipedia.org/wiki/Word2vec">Wikipedia</a>; <a href="https://arxiv.org/abs/1301.3781">Mikolov et al. (2013)</a>). If you enjoy mathematical explanations, the original papers are quite readable and interesting; if you would prefer a more library-centric explanation, read on.
</p>

<p>
  In traditional library cataloging, documents are assigned one or more subject headers (such as <a href="https://mit.worldcat.org/search?q=su%3ASpace+flight+Fiction">Space flight &mdash; Fiction</a>). You can find similar documents by looking for other documents with the same subject headers.
</p>

<p>
  We usually think of subject headers as a list &mdash; "here are the five subjects assigned to this book". However, we might instead think of them as a <em>vector</em>: "for each of the millions of possible subject headers, assign them a Boolean depending on whether they describe this book".
</p>

<p>
  Once you've got a vector rather than a list, though, there's no reason to restrict yourself to Booleans. Documents might be very much about some topics, and somewhat about others, a tiny bit about yet others, and not at all about the rest. For instance, one might end up with the following graph, situating science fiction books according to how much they're about gender and spaceships (tiny spoilers ahoy):
</p>


<img src="{% static 'img/gender_vs_spaceships.png' %}" alt="Graph of science fiction novels by amount of gender vs amount of spaceships"/>

<p>
  <em>Ancillary Justice</em> is very much about gender and also very much about spaceships. <em>Left Hand of Darkness</em> is also a lot about gender, but only a little bit (but more than zero) about spaceships. <em>The Martian</em> has basically no gender at all, and some spaceships, but not nearly as many as Mark Watney would like. Et cetera.
</p>

<p>
  You can imagine there might be more than two concepts, and therefore instead of a two-dimensional graph you could have a three-dimensional space (or four-dimensional, or four-hundred-dimensional...) Each document has a vector, with one number per concept, that pinpoints its coordinates in that space.
</p>

<p>
  Thinking about documents in this way gives you lots of interesting options. For instance, you can ask questions like, "Is <em>Ancillary Justice</em> more like <em>The Martian</em> or like <em>Star Wars</em>?" And you can get an answer that's literally a number &mdash; you can compare the distance between each book. You can also ask questions like "What do you get if you take <em>Star Wars</em> and add more gender?" or "If you start with <em>Ancillary Justice</em> and subtract out the stuff that's also in <em>Left Hand of Darkness</em>, what book is most like the parts that remain?" Because these questions all have mathematical meaning, computers can calculate their answers.
</p>

<p>
  Doc2Vec basically reads in documents and generates spaces like the one above, with two important exceptions:
</p>

<ol>
  <li>
    There are potentially hundreds of dimensions in the concept space, not just two (as on the graph above).
  </li>
  <li>
    Doc2Vec figures out the concept space as it goes, and it likely doesn't  map to meaningful human concepts like "gender" or "spaceships".
  </li>
</ol>

<p>
  So imagine a space that's hundreds of dimensions and doesn't have labels - but again, each document is a point in that space, and we can ask questions that are both semantically interesting and mathematically meaningful. "Which of these documents are most similar?" "If we started at one document and added or subtracted others, where would we end up?"
</p>

<p>
  The hamlet back end is a neural net that learned a concept space from the MIT thesis collection. The front end is where we ask questions.
</p>

<hr />

<h3><a id="team"></a>Who made this</h3>

<div class="layout-1q3q layout-band">
  <div class="col3q">
    <p>
      <b>Andromeda Yelton</b> is the lead for hamlet. She's a software engineer at the <a href="https://cyber.harvard.edu">Berkman Klein Center</a> (formerly at the <a href="https://libraries.mit.edu">MIT Libraries</a>) and the 2017-2018 President of the <a href="//www.lita.org">Library &amp; Information Technology Association.</a> She wrote most of the code: the machine learning; processing pipeline to extract fulltext and metadata from <a href="https://dspace.mit.edu">dSpace</a>; and the front and back ends of the Django app.
    </p>
  </div>
  <aside class="col1q">
    <img src="https://andromedayeltondotcom.files.wordpress.com/2010/05/andromeda-by-molly-color.jpg?w=600&h=400" alt="Andromeda's headshot">
  </aside>
</div>
<br />
<div class="layout-4q layout-band">
  <div class="col4q">
    <p>
      Thanks also go to the following:
    </p>
    <ul class="list-unbulleted">
      <li>
        🦄 <b>Frances Botsford</b>, who wrote the (modular, readable, wondrous) style system;
      </li>
      <li>
        🖥️ <b>Andy Dorner</b>, who set up the AWS pipeline;
      </li>
      <li>
        🧙‍ <b>Mike Graves</b>, who improved the file upload process and researched  citation processing options;
      </li>
      <li>
        🌈 <b>Helen Bailey</b>, whose dSpace extraction work I adapted, and who is hamlet's once and future data visualization wonk.
      </li>
      <li>
        🏛️ All the catalogers and techies who have added theses to dSpace and kept it going over the years.
      </li>
    </ul>
  </div>
</div>

<hr />

<h3><a id="tech"></a>The tech stack</h3>

<p>
  hamlet is a <a href="https://www.djangoproject.com/">Django</a> app, backed by a <a href="https://www.postgresql.org/">postgres</a> database and a neural net trained using <a href="https://radimrehurek.com/gensim/">gensim</a> on the fulltext of approximately 43,000 MIT graduate theses living in <a href="https://dspace.mit.edu/">dSpace@MIT</a>.
</p>

<p>
  Its code lives on <a href="https://github.com/thatandromeda/hamlet">GitHub</a> and it's hosted on <a href="https://aws.amazon.com/">AWS</a>.
</p>
{% endblock %}

hamlet/templates/base.html
{% load static %}
{% load compress %}

<!DOCTYPE html>
<!--[if lte IE 9]><html class="no-js lte-ie9" lang="en"><![endif]-->
<!--[if !(IE 8) | !(IE 9) ]><!-->
<html lang="en-US" class="no-js">
<!--<![endif]-->

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>How About Machine Learning Enhancing Theses?</title>

    <link rel="shortcut icon" href="/static/img/favicon.png">
    <link rel="apple-touch-icon" href="/static/img/favicon.png">

    <!-- mitlib-style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.1.1/normalize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic&subset=latin,latin-ext" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    {% compress css %}
      <link rel="stylesheet" type="text/x-sass" href='{% static "sass/hamlet.sass" %}'>
    {% endcompress %}


  </head>

  <body>
    <div class="wrap-page">
      <!-- begin alpha header -->
      <div class="wrap-notices info layout-band">
        <div class="wrap-notice">
          <div class="alert alert-global">
            Hamlet is in alpha. Things may change, break, or not make sense yet. Please enjoy anyway - and check back for more fun stuff to come!
          </div>
        </div>
      </div>
      <!-- end alpha -->

      <!-- begin hamlet branding -->
      <div class="wrap-outer-header layout-band layout-band-hamlet">
        <div class="wrap-content layout-3q1q">
          <h1 class="pull-left">
            <a href="/" class="logo">
              <img src="{% static "img/ai_logo_white.png" %}" />
            <span class="h1-text">HAMLET</span>
            <span class="subtitle">How About Machine Learning Enhancing Theses?</span>
          </a>
          </h1>
          <a class="button-secondary link-logo-mit" href="{% url 'about' %}">About</a>
        </div>
      </div>
      <!-- end hamlet branding -->

      <!-- begin main content -->
      <div class="wrap-outer-content layout-band">
        <div class="wrap-content layout-3q1q">
          <main id="content-main" class="content-main" role="main">
            {% block content %}

            {% endblock %}
          </main>
        </div>
      </div>
      <!-- end main content -->

      <!-- begin footer-->
      <div class="wrap-outer-footer-institute layout-band">
        <div class="wrap-footer-institute">
          <footer class="footer-info-institute" aria-label="footer" role="contentinfo">
            <div class="license">
              <ul class="list-unbulleted">
                <li>
                  Hamlet is a project by <a href="https://andromedayelton.com">Andromeda Yelton.</a>
                </li>
                <li>
                  <a href="https://github.com/thatandromeda/hamlet">Code</a> hosted with &hearts; on GitHub.
                </li>
                <li>
                  Hamlet logo by <a href="https://thenounproject.com/krisztian21/">Krisztián Mátyás</a> used under the <a href="http://creativecommons.org/licenses/by/3.0/" class="license-cc">Creative Commons Attribution License</a>.
                </li>
              </ul>
            </div>
          </footer><!-- end .footer-info-institute -->
        </div>
      </div>
      <!-- end footer-->
      {# This footer is for javascript included by child templates. #}
      {% block footer %}

      {% endblock %}
    </div>
  </body>
</html>

hamlet/templates/home.html
{% extends "base.html" %}

{% block content %}
  <div class="gridband layout-3c">
    <div class="grid-item">
      <div class="panel panel-info">
        <div class="panel-heading">
          <a href="{% url 'theses:similar_to' %}">Recommendation engine <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
        </div>
        <div class="panel-body">
          Given a thesis, find out which other theses are most conceptually
          similar.
        </div>
      </div>
    </div>

    <div class="grid-item">
      <div class="panel panel-info">
        <div class="panel-heading">
          <a href="{% url 'theses:upload_recommend' %}">Uploaded file oracle <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
        </div>
        <div class="panel-body">
          Upload a .txt or .docx file and find out which (if any) theses are conceptually
          similar.
        </div>
      </div>
    </div>

    <div class="grid-item">
      <div class="panel panel-info">
        <div class="panel-heading">
          <a href="{% url 'citations:lit_review_buddy' %}">Your literature review buddy <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
        </div>
        <div class="panel-body">
          <p>
            Upload a .txt or .docx file and find out what works have been cited by conceptually similar theses.
          </p>
          <p>
            That's right: we do your lit review for you.
          </p>
        </div>
      </div>
    </div>

  </div>
{% endblock %}

hamlet/templates/upload_form.html
{% for error in form.file.errors  %}
  <div class="alert alert-banner error">
    {{ error }}
  </div>
{% endfor %}

{% for error in form.captcha.errors  %}
  <div class="alert alert-banner error">
    {{ error }}
  </div>
{% endfor %}

<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="field-wrap">
    <label for="{{ form.file.id_for_label }}" class="field-label">{{ form.file.label }}</label>
    {{ form.file }}
    <p class="tip">
      {{ form.file.help_text}}
    </p>
  </div>
  <div class="field-wrap">
    <label for="{{ form.captcha.id_for_label }}" class="field-label">Type the letters</label>
    </br/>
    {{ form.captcha }}
    <p class="tip">
      No spammers, please.
    </p>
  </div>
  <div class="b-search-submit form-action">
    <button type="submit" class="btn button-primary">Upload</button>
  </div>
</form>